# -*- coding: utf-8 -*-
"""Project_Process_Book_17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTospxwKm2ZSUdqIWz4513NaoS4FpbO2

# ${\color{Blue}{(Project \ Topic):  }}$  จำนวนผู้เสียชีวิตจากอุบัติเหตุทางถนนของประเทศไทย ระหว่างปี 2560-2564

## ${\color{blue}{ แรงบรรดาลใจในการเลือกหัวข้อนี้ \ (Motivation): }}$

ในปัจจุบันเกิดอุบัติเหตุขึ้นบ่อยครั้ง ซึ่งทำให้เกิดการเสียชีวิตผู้จัดทำจึงมีความสนใจที่จะนำความรู้ในการเขียนโปรแกรมมาใช้ในการศึกษา สำรวจข้อมูลจำนวนผู้เสียชีวิตจากอุบัติเหตุทางถนนของประเทศไทย ระหว่างปี 2560-2564 เพื่อให้สรุปข้อมูลให้เข้าใจได้ง่ายมากขึ้น

#${\color{purple}{คำถามที่น่าสนใจเกี่ยวกับปัญหา \ (Interested \ Questions) :}}$

ลิตส์ของคำถามที่นักศึกษาร่วมกันอภิปรายแล้วให้ความสนใจ และต้องการหาคำตอบโดยอาศัยกระบวนการ Data Engineering and Data Science

---

1. จำนวนผู้เสียชีวิตจากบัติเหตุทางถนนของประเทศไทย ระหว่างปี 2560-2564 ในแต่ละปี
2. พาหนะใดบ้างที่เกิดอุบัติเหตุบนทางถนนของประเทศไทย ระหว่างปี 2560-2564
3. เพศใดบ้างที่เสียชีวิตจากการเกิดอุบัติเหตุทางถนนของประเทศไทย ระหว่างปี 2560-2564
4. อายุใดบ้างเสียชีวิตจากการเกิดอุบัติเหตุทางถนนของประเทศไทย ระหว่างปี 2560-2564

---

# ${\color{purple}{ข้อมูลที่เกี่ยวข้องในการใช้ตอบคำถามที่สนใจ}}$ ${\color{purple}{\ What \ are \ the \ Data \ related \ to \ answer \ the  \ questions? :}}$

# ${\color{pink}{ข้อมูลที่จะนำมาวิเคราะห์ \ (Dataset): }}$

*   1.	ปีที่เสียชีวิต(พศ.) (DEAD_YEAR(Budha))
    2.	อายุผู้เสียชีวิต (Age)
    3.	เพศผู้เสียชีวิต (Sex)
    4.	พาหนะที่ประสบเหตุตามรหัส ICD-10 (Vehicle)

## ${\color{pink}{แหล่งที่มาของข้อมูล:}}$

Dataset ที่ใช้นำมาจากไฟล์ .xlsx จาก https://data.go.th/en/dataset/rtddi?fbclid=IwAR0k_u_U9OHAbp8wyylAoZqRUIMalACW-M0Xqo60LEL69L9ys2F8sk5abBM

# ${\color{darkGrey}{Exploratory \ Data \  Analysis :}}$

## ${\color{Grey}{ Data \ acquisition \ process :}}$

*   แทนข้อความนี้ด้วยไอเดีย หรือกระบวนการในการได้มาซึ่งข้อมูล
"""

# Scrap/ Load and Preparing Data Set into Pandas DataFrame

# Commented out IPython magic to ensure Python compatibility.
# นำเข้าไลบรารีต่าง ๆ
# %matplotlib inline
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

!wget -q https://github.com/Phonbopit/sarabun-webfont/raw/master/fonts/thsarabunnew-webfont.ttf

# !pip install -U --pre matplotlib
import matplotlib as mpl
mpl.font_manager.fontManager.addfont('thsarabunnew-webfont.ttf')
mpl.rc('font', family='TH Sarabun New')

# ทำการโหลดไฟล์ จาก  Google drive ลงมาที่ current directory
!gdown --id 17vzuFnYPOWACtc0NgVbuAWv279sCFrdi
#https://docs.google.com/spreadsheets/d/17vzuFnYPOWACtc0NgVbuAWv279sCFrdi/edit?usp=sharing&ouid=109327518805005503397&rtpof=true&sd=true

# ทำการอ่านไฟล์สกุล xlsx
data = pd.read_excel("/content/tbl_rtddi .xlsx")
data

# เเสดงจำนวน Row และ Columns ของตาราง
data.shape

"""## ${\color{Grey}{ Data \ cleaning \ process :}}$

"""

# Checking and Cleaning your data

#เช็คข้อมูลหาความผิดปกติใน DataFrame
data.info()

#ลบคอลัมน์ที่ไม่ต้องการออก
data.drop(['id', 'DEAD_YEAR',"Time Rec", 'NationalityId',
       'Tumbol', 'District', 'Province', 'RiskHelmet', 'RiskSafetyBelt',
       'DeadDate', 'AccSubDist', 'AccDist','AccLat',"AccProv", 'AccLong', 'ICD-10', 'DateRec'], axis=1, inplace=True)

#เปลี่ยนชื่อ columns DEAD_YEAR(Budha)
data.rename(columns={'DEAD_YEAR(Budha)':'DeadYear'},inplace=True)

#เปลี่ยน type DeadYear และ Sex เป็น string
data['DeadYear'] = data['DeadYear'].astype('string')
data['Sex'] = data['Sex'].astype('string')
data['Vehicle'] = data['Vehicle'].astype('string')

#ข้อมูลใหม่ที่ต้องการ
data

data.info()

#เลือกข้อมูล 2560-2564
data = data[(data.DeadYear >= '2560') & (data.DeadYear <= '2564' ) ]
data

#ตรวจสอบค่าที่หายไป
print(data.isnull().sum())

#หาค่า mode median ที่จะแทนค่าลงไปแทนค่า Age , Sex ที่ NaN
df = data.copy()
val1 = df["Age"].median()
val2 = df["Sex"].mode().max()
val1, val2

#แทนค่า Age ที่ว่างด้วยค่า  median และ Sex ที่ว่าง ด้วยค่า mode
df["Age"].fillna(val1, inplace = True)
df["Sex"].fillna(val2, inplace = True)
df

#เช็คว่า Age มีค่ามากว่า 100 ไหม
df[df.Age > 100]

np.sum(df.Age > 100)

np.sum(df.Age < 0)

#ดูว่ามีค่านอกเกณฑ์ไหม
sns.boxplot(df.Age)

#จัดการกับค่าผิดปกติของ Age ด้วยสมการของ boxplots
#หาค่า Q1, Q3
q3 = df['Age'].quantile(.75)
q1 = df['Age'].quantile(.25)

#คำนวณหาช่วงข้อมูล Age
iqr = q3 - q1
upper = q3 + (1.5 * iqr)
lower = q1 - (1.5 * iqr)
print(f'q3 : {q3}\nq1 : {q1}\niqr : {iqr}')
print(f'upper : {upper}\nlower : {lower}')

#แสดงข้อมูล 2 รายการที่มีค่า Age > upper
outlier = df['Age'] > upper
df[outlier]

#ลบข้อมูล 2 รายการที่เป็นค่าผิดปกติของขอบบน
df.drop(df[outlier].index, inplace = True)
df

#แสดงข้อมูล 2 รายการที่มีค่า Age < lower
outlier = df['Age'] < lower
df[outlier]

#ลบข้อมูล 2 รายการที่เป็นค่าผิดปกติของขอบล่าง
df.drop(df[outlier].index, inplace = True )

#reset_index ให้เรียงลำดับ 0,1,2
df.reset_index(drop=True, inplace = True)
print(df)

sns.boxplot(df.Age)

#หาจำนวนข้อมูลแถวซ้ำกัน
np.sum(df.duplicated())

#ลบข้อมูลแถวซ้ำกัน
df.drop_duplicates(inplace = True)
df

#reset index ใหม่
df.reset_index(drop=True, inplace = True)
df

#แสดงข้อมูลสรุปทางสถิติของคอลัมน์
df.describe(include='all')

df['Age'].hist(bins = 10)
plt.title('Age')
plt.show()

#แสดงการแจกแจงของข้อมูล Age
sns.distplot(df['Age'], bins = 10)

#ในแต่ละปีนี้มีผู้เสียชีวิตจากอุบัติเหตุจำนวนเท่าใด
df.groupby('DeadYear').size()

#ดูว่าแต่ละอายุมีผู้เสียชีวิตจากอุบัติเหตุไปเท่าใด
df.groupby('Age').size()

#ดูว่าแต่ละเพศมีผู้เสียชีวิตจากอุบัติเหตุไปเท่าใด
df.groupby('Sex').size()

#ดูว่าพาหนะแต่ละชนิดเกิดอุบัติเหตุไปเท่าใด
df.groupby('Vehicle').size()

"""#Model

ปีพ.ศ.2560-2564
"""

df.DeadYear.value_counts().plot(kind="bar",figsize=(8, 8),fontsize = 12)
plt.title("Value counts of the DeadYear variable",fontsize=17)
plt.xlabel("Year",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

df.Vehicle.value_counts().plot(kind="barh",figsize=(10, 10),fontsize = 12)
plt.title("Value counts of the Vehicle variable",fontsize=17)
plt.xlabel("Count",fontsize=17)
plt.xticks(rotation=1)
plt.ylabel("Vehicle",fontsize=17)
plt.show()

df.Sex.value_counts().plot(kind="bar",figsize=(8, 8),fontsize = 12)
plt.title("Value counts of the Sex variable",fontsize=17)
plt.xlabel("Sex",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

df['Age'].hist(bins=[0,20,40,60,80,100])
plt.title("Value counts of the Age variable",fontsize=17)
plt.xlabel("Age",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

"""#ข้อมูลในแต่ละปี

ปี พ.ศ. 2560
"""

df60 = df[(df.DeadYear == '2560') ]

df60.Vehicle.value_counts()

df60.Sex.value_counts()

df60.Age.value_counts()

df60.Vehicle.value_counts().plot(kind="barh",figsize=(10, 10),fontsize = 12)
plt.title("Value counts of the Vehicle variable in 2560",fontsize=17)
plt.xlabel("Count",fontsize=17)
plt.xticks(rotation=1)
plt.ylabel("Vehicle",fontsize=17)
plt.show()

df60.Sex.value_counts().plot(kind="bar",figsize=(6, 6),fontsize = 12)
plt.title("Value counts of the Sex variable in 2560 ",fontsize=17)
plt.xlabel("Sex",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

df60['Age'].hist(bins=[0,20,40,60,80,100])
plt.title("Value counts of the Age variable in 2560",fontsize=17)
plt.xlabel("Age",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

"""ปี พ.ศ.2561"""

df61 = df[(df.DeadYear == '2561') ]

df61.Vehicle.value_counts()

df61.Sex.value_counts()

df61.Age.value_counts()

df61.Vehicle.value_counts().plot(kind="barh",figsize=(10, 10),fontsize = 12)
plt.title("Value counts of the Vehicle variable in 2561",fontsize=17)
plt.xlabel("Count",fontsize=17)
plt.xticks(rotation=1)
plt.ylabel("Vehicle",fontsize=17)
plt.show()


df61.Sex.value_counts().plot(kind="bar",figsize=(6, 6),fontsize = 12)
plt.title("Value counts of the Sex variable in 2561 ",fontsize=17)
plt.xlabel("Sex",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()


df61['Age'].hist(bins=[0,20,40,60,80,100])
plt.title("Value counts of the Age variable in 2561",fontsize=17)
plt.xlabel("Age",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

"""ปี พ.ศ.2562"""

df62 = df[(df.DeadYear == '2562') ]

df62.Vehicle.value_counts()

df62.Sex.value_counts()

df62.Age.value_counts()

df62.Vehicle.value_counts().plot(kind="barh",figsize=(10, 10),fontsize = 12)
plt.title("Value counts of the Vehicle variable in 2562",fontsize=17)
plt.xlabel("Count",fontsize=17)
plt.xticks(rotation=1)
plt.ylabel("Vehicle",fontsize=17)
plt.show()


df62.Sex.value_counts().plot(kind="bar",figsize=(6, 6),fontsize = 12)
plt.title("Value counts of the Sex variable in 2562 ",fontsize=17)
plt.xlabel("Sex",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()


df62['Age'].hist(bins=[0,20,40,60,80,100])
plt.title("Value counts of the Age variable in 2562",fontsize=17)
plt.xlabel("Age",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

"""ปี พ.ศ.2563"""

df63 = df[(df.DeadYear == '2563') ]

df63.Vehicle.value_counts()

df63.Sex.value_counts()

df63.Age.value_counts()

df63.Vehicle.value_counts().plot(kind="barh",figsize=(10, 10),fontsize = 12)
plt.title("Value counts of the Vehicle variable in 2563",fontsize=17)
plt.xlabel("Count",fontsize=17)
plt.xticks(rotation=1)
plt.ylabel("Vehicle",fontsize=17)
plt.show()


df63.Sex.value_counts().plot(kind="bar",figsize=(6, 6),fontsize = 12)
plt.title("Value counts of the Sex variable in 2563 ",fontsize=17)
plt.xlabel("Sex",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()


df63['Age'].hist(bins=[0,20,40,60,80,100])
plt.title("Value counts of the Age variable in 2563",fontsize=17)
plt.xlabel("Age",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()

"""ปี พ.ศ.2564"""

df64 = df[(df.DeadYear == '2564') ]

df64.Vehicle.value_counts()

df64.Sex.value_counts()

df64.Age.value_counts()

df64.Vehicle.value_counts().plot(kind="barh",figsize=(10, 10),fontsize = 12)
plt.title("Value counts of the Vehicle variable in 2564",fontsize=17)
plt.xlabel("Count",fontsize=17)
plt.xticks(rotation=1)
plt.ylabel("Vehicle",fontsize=17)
plt.show()


df64.Sex.value_counts().plot(kind="bar",figsize=(6, 6),fontsize = 12)
plt.title("Value counts of the Sex variable in 2564 ",fontsize=17)
plt.xlabel("Sex",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()


df64['Age'].hist(bins=[0,20,40,60,80,100])
plt.title("Value counts of the Age variable in 2564",fontsize=17)
plt.xlabel("Age",fontsize=17)
plt.xticks(rotation=0)
plt.ylabel("Count",fontsize=17)
plt.show()